import { Kit } from "@/types/Kits";

export const kits: Kit[] = [
    {
        id: "1",
        amount: "₦ 19,000",
        tag: "new",
        name: "Paris Saint-German",
        rating: "5.0",
        year: "2024/25 Home Kit",
        images: {
            preview: require("@/assets/images/kits/psg-1.jpeg"),
            "2": require("@/assets/images/kits/psg-2.jpeg"),
            "3": require("@/assets/images/kits/psg-3.jpeg"),
        },
    },
    {
        id: "2",
        amount: "₦ 19,000",
        tag: "new",
        name: "Liverpool F.C",
        rating: "5.0",
        year: "2024/25 Home Kit",
        images: {
            preview: require("@/assets/images/kits/liverpool-1.png"),
            "2": require("@/assets/images/kits/liverpool-2.png"),
            "3": require("@/assets/images/kits/liverpool-3.jpeg"),
        },
    },
    {
        id: "3",
        amount: "₦ 19,000",
        tag: "new",
        name: "F.C Barcelona",
        rating: "5.0",
        year: "2023/24 Home Kit",
        images: {
            preview: require("@/assets/images/kits/barcelona-1.png"),
            "2": require("@/assets/images/kits/barcelona-2.jpeg"),
            "3": require("@/assets/images/kits/barcelona-3.jpeg"),
            "4": require("@/assets/images/kits/barcelona-4.png"),
        },
    },
    {
        id: "4",
        amount: "₦ 15,000",
        tag: "new",
        name: "Nigeria",
        rating: "5.0",
        year: "2024 Away Kit",
        images: {
            preview: require("@/assets/images/kits/nigeria-preview.png"),
        },
    },
    {
        id: "5",
        amount: "₦ 19,000",
        tag: "new",
        name: "Chelsea F.C",
        rating: "5.0",
        year: "2023/24 Home Kit",
        images: {
            preview: require("@/assets/images/kits/chelsea-1.jpeg"),
            "2": require("@/assets/images/kits/chelsea-2.jpeg"),
            "3": require("@/assets/images/kits/chelsea-3.jpeg"),
            "4": require("@/assets/images/kits/chelsea-4.png"),
            "5": require("@/assets/images/kits/chelsea-5.png"),
        },
    },
    {
        id: "6",
        amount: "₦ 15,000",
        tag: "new",
        name: "Brazil",
        rating: "5.0",
        year: "2024 Home Kit",
        images: {
            preview: require("@/assets/images/kits/brazil-preview.png"),
        },
    },
    {
        id: "7",
        amount: "₦ 20,900",
        tag: "euro",
        name: "Belgium",
        rating: "5.0",
        year: "2024 Home Kit",
        images: {
            preview: require("@/assets/images/kits/belgium-preview.jpeg"),
        },
    },
    {
        id: "8",
        amount: "₦ 20,900",
        tag: "euro",
        name: "Germany",
        rating: "5.0",
        year: "2024 Home Kit",
        images: {
            preview: require("@/assets/images/kits/germany-preview.jpeg"),
        },
    },
    {
        id: "9",
        amount: "₦ 20,900",
        tag: "euro",
        name: "Spain",
        rating: "5.0",
        year: "2024 Home Kit",
        images: {
            preview: require("@/assets/images/kits/spain-preview.jpeg"),
        },
    },
    {
        id: "10",
        amount: "₦ 20,900",
        tag: "euro",
        name: "Italy",
        rating: "5.0",
        year: "2024 Home Kit",
        images: {
            preview: require("@/assets/images/kits/italy-preview.jpeg"),
        },
    },
    {
        id: "11",
        amount: "₦ 20,000",
        tag: "retro",
        name: "Bayern Unisex Retro",
        rating: "5.0",
        year: "1987-88 Kit",
        images: {
            preview: require("@/assets/images/kits/bayern-preview.jpeg"),
        },
    },
    {
        id: "12",
        amount: "₦ 20,000",
        tag: "retro",
        name: "Argentina Retro",
        rating: "5.0",
        year: "1994 Away Jersey",
        images: {
            preview: require("@/assets/images/kits/argentina-preview.jpeg"),
        },
    },
    {
        id: "13",
        amount: "₦ 20,000",
        tag: "featured",
        name: "Argentina Adidas Home Shirt 2024",
        rating: "5.0",
        year: "1994 Away Jersey",
        images: {
            preview: require("@/assets/images/kits/featured.gif"),
        },
    },
];
